name       : gl2ps
version    : 1.3.9
release    : 1
source     :
    - http://geuz.org/gl2ps/src/gl2ps-1.3.9.tgz : 8a680bff120df8bcd78afac276cdc38041fed617f2721bade01213362bcc3640
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : This is GL2PS, an OpenGL to PostScript printing library.
description: |
    This is GL2PS, an OpenGL to PostScript printing library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - texlive-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/libgl2ps.a
    rm $installdir/usr/share/doc/gl2ps/*.c
