name       : gl2ps
version    : 1.4.0
release    : 5
source     :
    - https://gitlab.onelab.info/gl2ps/gl2ps/-/archive/gl2ps_1_4_0/gl2ps-gl2ps_1_4_0.tar.gz : d74432070c744139b96ece10b8c4e6a1424e77dc5c44d6af671dd0592704d886
license    : GL2PS
component  : programming.library
summary    : This is GL2PS, an OpenGL to PostScript printing library
description: |
    This is GL2PS, an OpenGL to PostScript printing library.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(libpng)
    - pkgconfig(ptexenc)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/lib/libgl2ps.a
    rm $installdir/usr/share/doc/gl2ps/*.c
