name       : gl2ps
version    : 1.3.9
release    : 2
source     :
    - https://geuz.org/gl2ps/src/gl2ps-1.3.9.tgz : 8a680bff120df8bcd78afac276cdc38041fed617f2721bade01213362bcc3640
license    : GL2PS
component  : programming
summary    : This is GL2PS, an OpenGL to PostScript printing library
description: |
    This is GL2PS, an OpenGL to PostScript printing library.
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(ptexenc)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/libgl2ps.a
    rm $installdir/usr/share/doc/gl2ps/*.c
